#define STATUS_200 200, "Ok"
#define STATUS_404 404, "Not found"
#define STATUS_400 400, "Bad request"
#define CONFIG_DIR "/etc/wbsrv/"
#define DAEMON_NAME "webserver"
#define DEFAULTPAGE_FILENAME "index.html"
